/- Generated by generate_certificates.py. Every check uses Lean's kernel. -/
import CertificateSteps
set_option maxHeartbeats 0
set_option maxRecDepth 10000
namespace Graph20Proof
open RegularCertificate

@[irreducible] def certificate14 : FastCert := (.drop 0 (.drop 1 (.drop 2 (.drop 3 (.drop 4 (.drop 5 (.drop 6 (.drop 7 (.drop 8 (.drop 9 (.drop 10 (.drop 11 (.drop 12 (.drop 13 (.drop 14 .small)))))))))))))))
theorem certificate14_ok : fcheck 6 14 0 1048575 certificate14 = true := by
  unfold certificate14
  exact (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (by decide +kernel))))))))))))))))

theorem no_regular_14 (T : Finset (Fin 20)) (h : 6 ≤ T.card) :
    ¬ RegularOn neighbors T 14 :=
  fcheck_sound 14 certificate14 certificate14_ok T h
#print axioms no_regular_14
end Graph20Proof
