/- Generated by generate_certificates.py. Every check uses Lean's kernel. -/
import CertificateSteps
set_option maxHeartbeats 0
set_option maxRecDepth 10000
namespace Graph20Proof
open RegularCertificate

@[irreducible] def part8_0 : FastCert := (.split 17 (.split 18 (.split 19 (.split 15 (.split 16 (.split 12 (.split 14 (.split 5 (.fill 5 (.bad 17)) (.fill 14 (.bad 9))) (.fill 12 (.bad 7))) (.drop 7 (.drop 8 (.fill 16 (.bad 11))))) (.drop 5 (.drop 6 (.drop 7 (.fill 18 (.bad 9)))))) (.drop 6 (.drop 5 (.drop 8 (.fill 17 (.bad 9)))))) (.drop 5 (.drop 6 (.drop 7 (.fill 18 (.bad 9)))))) (.drop 5 (.drop 6 (.drop 7 (.drop 8 (.fill 17 (.bad 9))))))) (.drop 5 (.drop 6 (.drop 8 (.drop 7 (.drop 9 (.drop 10 (.drop 11 (.drop 12 (.drop 13 .small))))))))))
theorem part8_0_ok : fcheck 6 8 0 1048544 part8_0 = true := by
  unfold part8_0
  exact (accept_split (accept_split (accept_split (accept_split (accept_split (accept_split (accept_split (accept_split (accept_fill (by decide +kernel) (by decide +kernel)) (accept_fill (by decide +kernel) (by decide +kernel))) (accept_fill (by decide +kernel) (by decide +kernel))) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_fill (by decide +kernel) (by decide +kernel))))) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_fill (by decide +kernel) (by decide +kernel)))))) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_fill (by decide +kernel) (by decide +kernel)))))) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_fill (by decide +kernel) (by decide +kernel)))))) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_fill (by decide +kernel) (by decide +kernel))))))) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (by decide +kernel)))))))))))

@[irreducible] def certificate8 : FastCert := (.drop 0 (.drop 1 (.drop 2 (.drop 3 (.drop 4 part8_0)))))
theorem certificate8_ok : fcheck 6 8 0 1048575 certificate8 = true := by
  unfold certificate8
  exact (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) (accept_drop (by decide +kernel) part8_0_ok)))))

theorem no_regular_8 (T : Finset (Fin 20)) (h : 6 ≤ T.card) :
    ¬ RegularOn neighbors T 8 :=
  fcheck_sound 8 certificate8 certificate8_ok T h
#print axioms no_regular_8
end Graph20Proof
