/- Generated by generate_certificates.py. Every check uses Lean's kernel. -/
import CertificateSteps
set_option maxHeartbeats 0
set_option maxRecDepth 10000
namespace Graph20Proof
open RegularCertificate

@[irreducible] def part0_0 : FastCert := (.split 12 (.empty 12 (.split 4 (.empty 4 .small) (.split 0 (.empty 0 .small) .small))) (.split 11 (.empty 11 (.split 9 (.empty 9 .small) (.split 1 (.empty 1 .small) .small))) (.split 6 (.empty 6 (.split 9 (.empty 9 .small) (.split 1 (.empty 1 .small) .small))) (.split 3 (.empty 3 (.split 9 (.empty 9 .small) (.split 1 (.empty 1 .small) .small))) (.split 9 (.empty 9 (.split 0 (.empty 0 .small) .small)) (.split 0 (.empty 0 (.split 1 (.empty 1 .small) .small)) (.split 1 (.empty 1 .small) .small)))))))
theorem part0_0_ok : fcheck 6 0 0 31583 part0_0 = true := by
  unfold part0_0
  exact (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel)))) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel)))) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel)))) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel)))) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel))) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel))) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel))))))))

@[irreducible] def part0_1 : FastCert := (.split 17 (.empty 17 (.split 3 (.empty 3 (.split 4 (.empty 4 .small) .small)) (.split 4 (.empty 4 .small) .small))) (.split 7 (.empty 7 (.split 4 (.empty 4 .small) (.split 10 (.empty 10 .small) (.split 5 (.empty 5 .small) (.split 0 (.empty 0 .small) .small))))) (.split 10 (.empty 10 (.split 12 (.empty 12 .small) (.split 3 (.empty 3 .small) (.split 0 (.empty 0 .small) .small)))) (.split 5 (.empty 5 (.split 12 (.empty 12 .small) (.split 3 (.empty 3 .small) (.split 0 (.empty 0 .small) .small)))) part0_0))))
theorem part0_1_ok : fcheck 6 0 0 163839 part0_1 = true := by
  unfold part0_1
  exact (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel))) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel)))) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel)))))) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel))))) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel))))) part0_0_ok))))

@[irreducible] def certificate0 : FastCert := (.split 18 (.empty 18 .small) (.split 19 (.empty 19 .small) (.split 15 (.empty 15 (.split 7 (.empty 7 .small) (.split 1 (.empty 1 .small) .small))) (.split 16 (.empty 16 (.split 4 (.empty 4 (.split 9 (.empty 9 .small) .small)) (.split 9 (.empty 9 .small) .small))) part0_1))))
theorem certificate0_ok : fcheck 6 0 0 1048575 certificate0 = true := by
  unfold certificate0
  exact (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel)))) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel))) (accept_split (accept_empty (by decide +kernel) (by decide +kernel)) (by decide +kernel)))) part0_1_ok))))

theorem no_regular_0 (T : Finset (Fin 20)) (h : 6 ≤ T.card) :
    ¬ RegularOn neighbors T 0 :=
  fcheck_sound 0 certificate0 certificate0_ok T h
#print axioms no_regular_0
end Graph20Proof
