"""Produce untrusted branch certificates and explicit kernel-checked Lean terms.

The proof checker and composition lemmas are adapted from JSP PR #190.
The generator's output is not assumed correct: Lean checks every branch step.
"""
from pathlib import Path
import hashlib
import json
from verify_witness import decode_masks

ROOT = Path(__file__).resolve().parent
N, K = 20, 6
FULL = (1 << N) - 1
ADJ = decode_masks((ROOT / "witness20.g6").read_bytes())


def bits(mask):
    while mask:
        bit = mask & -mask
        yield bit.bit_length() - 1
        mask ^= bit


def generate(degree):
    definitions = []
    stats = {name: 0 for name in ("small", "bad", "drop", "fill", "empty", "split")}

    def package(name, expression, selected, possible, proof):
        definitions.append(
            f"@[irreducible] def {name} : FastCert := {expression}\n"
            f"theorem {name}_ok : fcheck {K} {degree} {selected} {possible} {name} = true := by\n"
            f"  unfold {name}\n  exact {proof}\n"
        )

    def walk(selected, possible):
        assert selected & possible == selected
        tag, vertex, states = None, None, []
        if possible.bit_count() < K:
            tag = "small"
        else:
            for v in bits(selected):
                low, high = (ADJ[v] & selected).bit_count(), (ADJ[v] & possible).bit_count()
                if low > degree or high < degree:
                    tag, vertex = "bad", v
                    break
            if tag is None:
                for v in bits(selected):
                    changing = ADJ[v] & possible & ~selected
                    if not changing:
                        continue
                    if (ADJ[v] & selected).bit_count() == degree:
                        tag, vertex, states = "empty", v, [(selected, possible & ~changing)]
                        break
                    if (ADJ[v] & possible).bit_count() == degree:
                        tag, vertex, states = "fill", v, [(selected | changing, possible)]
                        break
            if tag is None:
                for v in bits(possible & ~selected):
                    if (ADJ[v] & selected).bit_count() > degree or (ADJ[v] & possible).bit_count() < degree:
                        tag, vertex, states = "drop", v, [(selected, possible & ~(1 << v))]
                        break
            if tag is None:
                free = list(bits(possible & ~selected))
                if not free:
                    raise ValueError(f"Actual regular subset encountered: {selected}, degree={degree}")
                vertex = max(free, key=lambda v: ((ADJ[v] & selected).bit_count(), (ADJ[v] & possible).bit_count(), -v))
                tag, states = "split", [(selected | (1 << vertex), possible), (selected, possible & ~(1 << vertex))]
        stats[tag] += 1
        children = [walk(*state) for state in states]
        expression = ".small" if tag == "small" else f"(.{tag} {vertex}" + "".join(" " + child[0] for child in children) + ")"
        size = 1 + sum(child[1] for child in children)
        if tag in ("small", "bad"):
            proof = "(by decide +kernel)"
        elif tag == "split":
            proof = f"(accept_split {children[0][2]} {children[1][2]})"
        else:
            proof = f"(accept_{tag} (by decide +kernel) {children[0][2]})"
        if size > 45:
            name = f"part{degree}_{len(definitions)}"
            package(name, expression, selected, possible, proof)
            return name, 1, name + "_ok"
        return expression, size, proof

    expression, _, proof = walk(0, FULL)
    package(f"certificate{degree}", expression, 0, FULL, proof)
    text = (
        "/- Generated by generate_certificates.py. Every check uses Lean's kernel. -/\n"
        "import CertificateSteps\nset_option maxHeartbeats 0\nset_option maxRecDepth 10000\n"
        "namespace Graph20Proof\nopen RegularCertificate\n\n"
        + "\n".join(definitions)
        + f"\ntheorem no_regular_{degree} (T : Finset (Fin {N})) (h : {K} ≤ T.card) :\n"
        + f"    ¬ RegularOn neighbors T {degree} :=\n"
        + f"  fcheck_sound {degree} certificate{degree} certificate{degree}_ok T h\n"
        + f"#print axioms no_regular_{degree}\nend Graph20Proof\n"
    )
    return text, stats


def main():
    records = []
    for d in range(N):
        text, stats = generate(d)
        path = ROOT / f"Degree{d}.lean"
        path.write_text(text)
        records.append({"degree": d, "nodes": sum(stats.values()), "node_types": stats,
                        "bytes": len(text.encode()), "sha256": hashlib.sha256(text.encode()).hexdigest()})
    (ROOT / "certificate-generation.json").write_text(json.dumps(records, indent=2) + "\n")
    print(json.dumps({"modules": len(records), "nodes": sum(r["nodes"] for r in records),
                      "source_bytes": sum(r["bytes"] for r in records)}))


if __name__ == "__main__":
    main()
