import Mathlib

-- Generated by make_standalone.py; generation is not Lean verification.
-- Declaration bodies below are copied exactly from the canonical modules.

-- BEGIN EXACT ARITHMETIC BODY

/-!
Arithmetic components of the half-residue sieve counterexample.
These declarations use only Lean's core library, not Mathlib.
The accompanying verification report records the exact compiler environment.
-/

set_option maxHeartbeats 2000000
set_option maxRecDepth 4096

public section

namespace JSP001007.Arithmetic


theorem window_point_mod
    (M J H p j s : Nat)
    (hM : 64 ≤ M) (hH : 8 * H ≤ M) (hD : 8 * J * H ≤ M)
    (hpL : M ≤ p) (hpU : p ≤ M + H)
    (hj : j < J) (hs : s < M / 4) :
    p / 2 ≤ (j * M + 3 * (M / 4) + s) % p := by
  let T := M / 4
  let x := j * M + 3 * T + s
  have hTlo : 4 * T ≤ M := by dsimp [T]; omega
  have hThi : M ≤ 4 * T + 3 := by dsimp [T]; omega
  have hsT : s < T := hs
  have hhalf : 2 * (p / 2) ≤ p := by omega
  have hD' : 8 * (J * H) ≤ M := by simpa only [Nat.mul_assoc] using hD
  have hbuffer : J * H + p / 2 ≤ 3 * T := by omega
  have hjp : j * p ≤ j * M + J * H := by
    calc
      j * p ≤ j * (M + H) := Nat.mul_le_mul_left j hpU
      _ = j * M + j * H := Nat.mul_add _ _ _
      _ ≤ j * M + J * H :=
        Nat.add_le_add_left (Nat.mul_le_mul_right H (Nat.le_of_lt hj)) _
  have hxL : j * p + p / 2 ≤ x := by dsimp [x]; omega
  have hjbase : j * M ≤ j * p := Nat.mul_le_mul_left j hpL
  have ht : 3 * T + s < M := by omega
  have hxU : x < j * p + p := by dsimp [x]; omega
  have hrU : x - j * p < p := by omega
  have hdecomp : j * p + (x - j * p) = x := by omega
  have hmod : x % p = x - j * p := by
    calc
      x % p = (j * p + (x - j * p)) % p := by simp only [hdecomp]
      _ = x - j * p := by simp [Nat.add_mod, Nat.mod_eq_of_lt hrU]
  change p / 2 ≤ x % p
  rw [hmod]
  omega

theorem window_point_in_interval (M J j s : Nat)
    (hM : 64 ≤ M) (hj : j < J) (hs : s < M / 4) :
    1 ≤ j * M + 3 * (M / 4) + s ∧
    j * M + 3 * (M / 4) + s ≤ J * M := by
  have hTlo : 4 * (M / 4) ≤ M := by omega
  have hTpos : 0 < M / 4 := by omega
  have hlast : (j + 1) * M ≤ J * M :=
    Nat.mul_le_mul_right M (by omega : j + 1 ≤ J)
  simp only [Nat.add_mul, Nat.one_mul] at hlast
  omega

theorem window_points_injective (M j k s t : Nat)
    (hM : 64 ≤ M) (hs : s < M / 4) (ht : t < M / 4)
    (he : j * M + 3 * (M / 4) + s = k * M + 3 * (M / 4) + t) :
    j = k ∧ s = t := by
  have hTlo : 4 * (M / 4) ≤ M := by omega
  have hds : 3 * (M / 4) + s < M := by omega
  have hdt : 3 * (M / 4) + t < M := by omega
  have he' : j * M + (3 * (M / 4) + s) =
      k * M + (3 * (M / 4) + t) := by omega
  have hm := congrArg (fun n : Nat => n % M) he'
  have hd : 3 * (M / 4) + s = 3 * (M / 4) + t := by
    simpa [Nat.add_mod, Nat.mod_eq_of_lt hds, Nat.mod_eq_of_lt hdt] using hm
  have hst : s = t := by omega
  have hjk : j * M = k * M := by omega
  exact ⟨Nat.eq_of_mul_eq_mul_right (by omega : 0 < M) hjk, hst⟩

theorem window_density (M : Nat) (hM : 64 ≤ M) : M < 10 * (M / 4) := by
  omega

private theorem pow_two (q : Nat) : Nat.pow q 2 = q * q := Nat.pow_two q
private theorem mul_pow (a b n : Nat) :
    Nat.pow (a * b) n = Nat.pow a n * Nat.pow b n := Nat.mul_pow a b n
private theorem pow_mul (a m n : Nat) :
    Nat.pow a (m * n) = Nat.pow (Nat.pow a m) n := Nat.pow_mul a m n
private theorem pow_add (a m n : Nat) :
    Nat.pow a (m + n) = Nat.pow a m * Nat.pow a n := Nat.pow_add a m n
private theorem pow_succ (a n : Nat) :
    Nat.pow a (n + 1) = Nat.pow a n * a := Nat.pow_succ a n

theorem cluster_conditions (q : Nat) (hq : 1000000000000 ≤ q) :
    64 ≤ Nat.pow q 2 ∧ 0 < q / 100 ∧
    8 * (2 * q + 1) ≤ Nat.pow q 2 ∧
    8 * (q / 100) * (2 * q + 1) ≤ Nat.pow q 2 ∧ q ≤ Nat.pow q 2 := by
  let J := q / 100
  have hqM : q ≤ Nat.pow q 2 := by
    rw [pow_two]
    exact Nat.le_mul_self q
  have hM : 64 ≤ Nat.pow q 2 := by omega
  have hJ : 0 < J := by dsimp [J]; omega
  have hJbound : 100 * J ≤ q := by dsimp [J]; omega
  have hq17 : 17 * q ≤ q * q :=
    Nat.mul_le_mul_right q (by omega : 17 ≤ q)
  have hH : 8 * (2 * q + 1) ≤ Nat.pow q 2 := by
    rw [pow_two]
    omega
  have h100 : 100 * (J * q) ≤ q * q := by
    simpa only [Nat.mul_assoc] using Nat.mul_le_mul_right q hJbound
  have hJq : J ≤ J * q := by
    simpa only [Nat.mul_one] using
      Nat.mul_le_mul_left J (by omega : 1 ≤ q)
  have hcoef : 8 * J * 2 = 16 * J := by omega
  have hid : 8 * J * (2 * q + 1) = 16 * (J * q) + 8 * J := by
    rw [Nat.mul_add, ← Nat.mul_assoc, hcoef, Nat.mul_one, Nat.mul_assoc] <;> rfl
  have hD : 8 * J * (2 * q + 1) ≤ Nat.pow q 2 := by
    rw [hid, pow_two]
    omega
  exact ⟨hM, hJ, hH, hD, hqM⟩

theorem cluster_cutoff_four {q p : Nat}
    (hq : 1000000000000 ≤ q) (hp : p ≤ Nat.pow (q + 1) 2) :
    Nat.pow p 4 < Nat.pow ((q / 100) * Nat.pow q 2) 3 := by
  let J := q / 100
  have hJpos : 0 < J := by dsimp [J]; omega
  have hJlarge : 10240000 < J := by dsimp [J]; omega
  have hqJ : q ≤ 200 * J := by dsimp [J]; omega
  have hcore : 256 * Nat.pow q 2 < Nat.pow J 3 := by
    calc
      256 * Nat.pow q 2 ≤ 256 * Nat.pow (200 * J) 2 :=
        Nat.mul_le_mul_left 256 (Nat.pow_le_pow_left hqJ 2)
      _ = 10240000 * Nat.pow J 2 := by
        rw [mul_pow, ← Nat.mul_assoc] <;> rfl
      _ < J * Nat.pow J 2 :=
        Nat.mul_lt_mul_of_pos_right hJlarge (Nat.pow_pos hJpos)
      _ = Nat.pow J 3 :=
        (Nat.mul_comm J (Nat.pow J 2)).trans (pow_succ J 2).symm
  have hsquare : Nat.pow (q + 1) 2 ≤ 4 * Nat.pow q 2 := by
    have hh := Nat.pow_le_pow_left (by omega : q + 1 ≤ 2 * q) 2
    calc
      Nat.pow (q + 1) 2 ≤ Nat.pow (2 * q) 2 := hh
      _ = 4 * Nat.pow q 2 := by rw [mul_pow] <;> rfl
  have hp' : p ≤ 4 * Nat.pow q 2 := Nat.le_trans hp hsquare
  calc
    Nat.pow p 4 ≤ Nat.pow (4 * Nat.pow q 2) 4 := Nat.pow_le_pow_left hp' 4
    _ = 256 * Nat.pow q 8 := by rw [mul_pow, ← pow_mul] <;> rfl
    _ = (256 * Nat.pow q 2) * Nat.pow q 6 := by
      rw [Nat.mul_assoc, ← pow_add] <;> rfl
    _ < Nat.pow J 3 * Nat.pow q 6 :=
      Nat.mul_lt_mul_of_pos_right hcore (Nat.pow_pos (by omega : 0 < q))
    _ = Nat.pow (J * Nat.pow q 2) 3 := by rw [mul_pow, ← pow_mul] <;> rfl

theorem cutoff_ten {p N : Nat} (hp : 1 ≤ p)
    (h : Nat.pow p 4 < Nat.pow N 3) : Nat.pow p 10 < Nat.pow N 9 := by
  have h12 : Nat.pow p 12 < Nat.pow N 9 := by
    calc
      Nat.pow p 12 = Nat.pow (Nat.pow p 4) 3 := pow_mul p 4 3
      _ < Nat.pow (Nat.pow N 3) 3 := Nat.pow_lt_pow_left h (by decide : (3 : Nat) ≠ 0)
      _ = Nat.pow N 9 := (pow_mul N 3 3).symm
  exact Nat.lt_of_le_of_lt
    (Nat.pow_le_pow_right (by omega : 0 < p) (by decide : (10 : Nat) ≤ 12)) h12

end JSP001007.Arithmetic

#print axioms JSP001007.Arithmetic.window_point_mod
#print axioms JSP001007.Arithmetic.window_point_in_interval
#print axioms JSP001007.Arithmetic.window_points_injective
#print axioms JSP001007.Arithmetic.window_density
#print axioms JSP001007.Arithmetic.cluster_conditions
#print axioms JSP001007.Arithmetic.cluster_cutoff_four
#print axioms JSP001007.Arithmetic.cutoff_ten

-- END EXACT ARITHMETIC BODY

-- BEGIN EXACT PRIME BLOCKS BODY

/-!
# Prime blocks for JSP-001007

Repair revision: explicit finite-block HasSum certificates, including q = 0.
This module is independently compilable. Its two transitive axiom reports
must pass before the downstream sieve construction is accepted.
See VERIFICATION.md for the actual verification status of this revision.
-/

set_option maxHeartbeats 2000000
set_option maxRecDepth 4096

open scoped BigOperators

namespace JSP001007

/-- The primes in the half-open interval [q^2, (q+1)^2). -/
def primeBlock (q : ℕ) : Finset ℕ :=
  (Finset.Ico (q ^ 2) ((q + 1) ^ 2)).filter Nat.Prime

/-- The first square interval contains only 0, which is not prime. -/
@[simp]
lemma primeBlock_zero : primeBlock 0 = ∅ := by
  decide

private noncomputable def blockWeight (q : ℕ) : ℝ :=
  ∑ p ∈ primeBlock q, (1 : ℝ) / p

private lemma blockWeight_nonneg (q : ℕ) : 0 ≤ blockWeight q := by
  exact Finset.sum_nonneg fun _ _ => by positivity

private lemma blockWeight_le (C q : ℕ)
    (hc : (primeBlock q).card ≤ C) :
    blockWeight q ≤ (C : ℝ) * ((q : ℝ) ^ 2)⁻¹ := by
  by_cases hq : q = 0
  · subst q
    simp [blockWeight]
  have hqpos : 0 < (q : ℝ) ^ 2 := by positivity
  calc
    blockWeight q ≤ ∑ _p ∈ primeBlock q, ((q : ℝ) ^ 2)⁻¹ := by
      apply Finset.sum_le_sum
      intro p hp
      have hqp : q ^ 2 ≤ p :=
        (Finset.mem_Ico.mp (Finset.mem_filter.mp hp).1).1
      have hqpR : (q : ℝ) ^ 2 ≤ (p : ℝ) := by exact_mod_cast hqp
      simpa only [one_div] using one_div_le_one_div_of_le hqpos hqpR
    _ = ((primeBlock q).card : ℝ) * ((q : ℝ) ^ 2)⁻¹ := by
      simp only [Finset.sum_const, nsmul_eq_mul]
    _ ≤ (C : ℝ) * ((q : ℝ) ^ 2)⁻¹ := by
      exact mul_le_mul_of_nonneg_right (by exact_mod_cast hc) (by positivity)

/-- A uniform bound on the number of primes in square intervals would make
    the sum of prime reciprocals converge. -/
theorem primeBlock_card_unbounded (C : ℕ) :
    ∃ q : ℕ, C < (primeBlock q).card := by
  classical
  by_contra h
  push_neg at h
  have hmajorant : Summable (fun q : ℕ => (C : ℝ) * ((q : ℝ) ^ 2)⁻¹) :=
    (Real.summable_nat_pow_inv.mpr (by norm_num : 1 < (2 : ℕ))).mul_left _
  have hw : Summable blockWeight :=
    hmajorant.of_nonneg_of_le blockWeight_nonneg (fun q => blockWeight_le C q (h q))
  -- Use exactly the indicator appearing in Mathlib's divergence theorem.
  let f : ℕ → ℝ :=
    Set.indicator {n : ℕ | n.Prime} (fun n => (1 : ℝ) / n)
  have hf : 0 ≤ f := by
    intro n
    exact Set.indicator_nonneg (fun _ _ => by positivity) n
  have hpartition : ∀ n : ℕ, ∃! q : ℕ,
      n ∈ (↑(Finset.Ico (q ^ 2) ((q + 1) ^ 2)) : Set ℕ) := by
    intro n
    refine ⟨n.sqrt, ?_, ?_⟩
    · simpa only [Finset.mem_coe, Finset.mem_Ico] using
        (Nat.eq_sqrt'.mp (rfl : n.sqrt = n.sqrt))
    · intro q hq
      exact Nat.eq_sqrt'.mpr (by
        simpa only [Finset.mem_coe, Finset.mem_Ico] using hq)
  -- Finset.hasSum supplies both finite-fiber summability and its exact sum.
  -- No nonexistent `summable_fintype`, no implicit tsum/subtype conversion.
  have hblock (q : ℕ) : HasSum
      (fun n : (↑(Finset.Ico (q ^ 2) ((q + 1) ^ 2)) : Set ℕ) => f n)
      (blockWeight q) := by
    have hsum : (∑ n ∈ Finset.Ico (q ^ 2) ((q + 1) ^ 2), f n) =
        blockWeight q := by
      simp only [f, Set.indicator_apply, Set.mem_setOf_eq,
        blockWeight, primeBlock, Finset.sum_filter]
    rw [← hsum]
    exact (Finset.Ico (q ^ 2) ((q + 1) ^ 2)).hasSum f
  have houter_eq :
      (fun q : ℕ =>
        ∑' n : (↑(Finset.Ico (q ^ 2) ((q + 1) ^ 2)) : Set ℕ), f n) =
      blockWeight := by
    funext q
    exact (hblock q).tsum_eq
  have houter : Summable (fun q : ℕ =>
      ∑' n : (↑(Finset.Ico (q ^ 2) ((q + 1) ^ 2)) : Set ℕ), f n) := by
    rw [houter_eq]
    exact hw
  have hall : Summable f :=
    (summable_partition (f := f) (s := fun q : ℕ =>
      (↑(Finset.Ico (q ^ 2) ((q + 1) ^ 2)) : Set ℕ)) hf hpartition).mpr
      ⟨fun q => (hblock q).summable, houter⟩
  exact not_summable_one_div_on_primes hall

/-- The square interval can be required to lie arbitrarily far out. -/
theorem large_primeBlock (K Q : ℕ) :
    ∃ q : ℕ, Q ≤ q ∧ K ≤ (primeBlock q).card := by
  obtain ⟨q, hq⟩ := primeBlock_card_unbounded (K + (Q + 1) ^ 2)
  refine ⟨q, ?_, by omega⟩
  have hsub : primeBlock q ⊆ Finset.range ((q + 1) ^ 2) := by
    intro p hp
    exact Finset.mem_range.mpr
      (Finset.mem_Ico.mp (Finset.mem_filter.mp hp).1).2
  have hcard : (primeBlock q).card ≤ (q + 1) ^ 2 := by
    simpa only [Finset.card_range] using Finset.card_le_card hsub
  by_contra hsmall
  have hqQ : q + 1 ≤ Q + 1 := by omega
  have hsquares : (q + 1) ^ 2 ≤ (Q + 1) ^ 2 :=
    Nat.pow_le_pow_left hqQ 2
  omega

#print axioms JSP001007.primeBlock_card_unbounded
#print axioms JSP001007.large_primeBlock

end JSP001007

-- END EXACT PRIME BLOCKS BODY

-- BEGIN EXACT MAIN BODY

/-!
# JSP-001007 / the uniform half-residue sieve question

This repair keeps the arithmetic and downstream construction unchanged, and
isolates the repaired prime-block argument in JSP001007.PrimeBlocks.
The original revision failed native compilation, as reported by the user.
A repair is not a successful compiler run: see VERIFICATION.md for this
revision's actual compilation and transitive-axiom audit status.

The argument is independent of the unproved declarations in
FormalConjectures/GreensOpenProblems/44.lean.

Main statement: for every k and every lower bound N0, there are k distinct odd
primes below N^(9/10), and sets of exactly half their residue classes, leaving
strictly more than N/10 integers in [1,N].

The only global number-theoretic input is Mathlib's proved divergence of the
sum of the reciprocals of the primes. No additional axioms are introduced.
-/

set_option maxHeartbeats 2000000
set_option maxRecDepth 4096

open scoped BigOperators

namespace JSP001007

/-- Remove the initial floor(p/2) residue classes. -/
def forbidden (p : ℕ) : Finset (ZMod p) :=
  (Finset.range (p / 2)).image (fun a : ℕ => (a : ZMod p))

lemma forbidden_card (p : ℕ) : (forbidden p).card = p / 2 := by
  classical
  have hinj : Set.InjOn (fun a : ℕ => (a : ZMod p)) (Finset.range (p / 2)) := by
    intro a ha b hb hab
    have hap : a < p :=
      (Finset.mem_range.mp ha).trans_le (Nat.div_le_self p 2)
    have hbp : b < p :=
      (Finset.mem_range.mp hb).trans_le (Nat.div_le_self p 2)
    have hv := congrArg ZMod.val hab
    simpa only [ZMod.val_natCast, Nat.mod_eq_of_lt hap,
      Nat.mod_eq_of_lt hbp] using hv
  exact (Finset.card_image_of_injOn hinj).trans (Finset.card_range _)

lemma avoids_forbidden_of_mod_ge (x p : ℕ) (h : p / 2 ≤ x % p) :
    (x : ZMod p) ∉ forbidden p := by
  intro hx
  obtain ⟨a, ha, he⟩ := Finset.mem_image.mp hx
  have ha' : a < p / 2 := Finset.mem_range.mp ha
  have hap : a < p := ha'.trans_le (Nat.div_le_self p 2)
  have hv := congrArg ZMod.val he
  simp only [ZMod.val_natCast, Nat.mod_eq_of_lt hap] at hv
  omega

/-- The same survivor-set definition as the half-residue sieve framework. -/
def remaining {k : ℕ} (N : ℕ) (p : Fin k → ℕ)
    (A : (i : Fin k) → Finset (ZMod (p i))) : Finset ℕ :=
  (Finset.Icc 1 N).filter (fun x => ∀ i, (x : ZMod (p i)) ∉ A i)

/-- An individual point in the common high-residue window survives every
    modulus in a sufficiently narrow cluster. -/
private lemma window_point_avoids
    (M J H p j s : ℕ)
    (hM : 64 ≤ M) (hH : 8 * H ≤ M) (hD : 8 * J * H ≤ M)
    (hpL : M ≤ p) (hpU : p ≤ M + H)
    (hj : j < J) (hs : s < M / 4) :
    ((j * M + 3 * (M / 4) + s : ℕ) : ZMod p) ∉ forbidden p := by
  exact avoids_forbidden_of_mod_ge _ _
    (Arithmetic.window_point_mod M J H p j s hM hH hD hpL hpU hj hs)

/-- Counting a rectangular set of surviving points; all floor effects are
    included, rather than discarded in an asymptotic estimate. -/
theorem window_card_bound {k : ℕ} (M J H : ℕ) (p : Fin k → ℕ)
    (hM : 64 ≤ M) (hH : 8 * H ≤ M) (hD : 8 * J * H ≤ M)
    (hpL : ∀ i, M ≤ p i) (hpU : ∀ i, p i ≤ M + H) :
    J * (M / 4) ≤
      (remaining (J * M) p (fun i => forbidden (p i))).card := by
  classical
  let T : ℕ := M / 4
  let rectangle := (Finset.range J).product (Finset.range T)
  let f : ℕ × ℕ → ℕ := fun a => a.1 * M + 3 * T + a.2
  let S : Finset ℕ := rectangle.image f
  have hinj : Set.InjOn f rectangle := by
    intro a ha b hb hab
    have haS : a.2 < T :=
      Finset.mem_range.mp (Finset.mem_product.mp ha).2
    have hbS : b.2 < T :=
      Finset.mem_range.mp (Finset.mem_product.mp hb).2
    have hpair := Arithmetic.window_points_injective M a.1 b.1 a.2 b.2
      hM haS hbS hab
    exact Prod.ext hpair.1 hpair.2

  have hcard : S.card = J * T := by
    calc
      S.card = rectangle.card := Finset.card_image_of_injOn hinj
      _ = J * T := by simp [rectangle]
  have hsub : S ⊆ remaining (J * M) p (fun i => forbidden (p i)) := by
    intro x hx
    obtain ⟨a, ha, rfl⟩ := Finset.mem_image.mp hx
    have haJ : a.1 < J :=
      Finset.mem_range.mp (Finset.mem_product.mp ha).1
    have haS : a.2 < T :=
      Finset.mem_range.mp (Finset.mem_product.mp ha).2
    have hinterval := Arithmetic.window_point_in_interval M J a.1 a.2 hM haJ haS
    apply Finset.mem_filter.mpr
    refine ⟨Finset.mem_Icc.mpr hinterval, ?_⟩
    intro i
    exact window_point_avoids M J H (p i) a.1 a.2
      hM hH hD (hpL i) (hpU i) haJ haS
  calc
    J * (M / 4) = S.card := hcard.symm
    _ ≤ _ := Finset.card_le_card hsub

/-- Full quantified counterexample, including arbitrarily large N.

In particular, k is NOT fixed to 1000. All moduli are distinct odd primes.
-/
theorem counterexamples (k N0 : ℕ) :
    ∃ (N : ℕ) (p : Fin k → ℕ)
      (A : (i : Fin k) → Finset (ZMod (p i))),
      N0 ≤ N ∧
      (∀ i, (p i).Prime ∧ 2 < p i) ∧
      StrictMono p ∧
      (∀ i, (p i) ^ 10 < N ^ 9) ∧
      (∀ i, (A i).card = (p i) / 2) ∧
      N < 10 * (remaining N p A).card := by
  classical
  obtain ⟨q, hq, hcount⟩ := large_primeBlock k (1000000000000 + N0)
  have hqbig : 1000000000000 ≤ q := by omega
  let M : ℕ := q ^ 2
  let J : ℕ := q / 100
  let H : ℕ := 2 * q + 1
  let N : ℕ := J * M
  let e : Fin k ↪o ℕ := (primeBlock q).orderEmbOfCardLe hcount
  let p : Fin k → ℕ := e
  let A : (i : Fin k) → Finset (ZMod (p i)) := fun i => forbidden (p i)
  have hpBlock (i : Fin k) : p i ∈ primeBlock q :=
    Finset.orderEmbOfCardLe_mem (primeBlock q) hcount i
  have hpPrime (i : Fin k) : (p i).Prime :=
    (Finset.mem_filter.mp (hpBlock i)).2
  have hpL (i : Fin k) : M ≤ p i :=
    (Finset.mem_Ico.mp (Finset.mem_filter.mp (hpBlock i)).1).1
  have hpSquare (i : Fin k) : p i < (q + 1) ^ 2 :=
    (Finset.mem_Ico.mp (Finset.mem_filter.mp (hpBlock i)).1).2
  have hpU (i : Fin k) : p i ≤ M + H := by
    have ht := hpSquare i
    dsimp [M, H]
    nlinarith
  have hconditions : 64 ≤ M ∧ 0 < J ∧ 8 * H ≤ M ∧
      8 * J * H ≤ M ∧ q ≤ M := Arithmetic.cluster_conditions q hqbig
  obtain ⟨hM, hJ, hH, hD, hqM⟩ := hconditions
  have hMN : M ≤ N := by
    have hm := Nat.mul_le_mul_right M (by omega : 1 ≤ J)
    simpa only [one_mul, N] using hm
  have hN0 : N0 ≤ N := by omega
  have hsurv := window_card_bound M J H p hM hH hD hpL hpU
  have hratio : M < 10 * (M / 4) := Arithmetic.window_density M hM
  have hdensity : N < 10 * (remaining N p A).card := by
    calc
      N < J * (10 * (M / 4)) := Nat.mul_lt_mul_of_pos_left hratio hJ
      _ = 10 * (J * (M / 4)) := by ring
      _ ≤ 10 * (remaining N p A).card := Nat.mul_le_mul_left 10 hsurv
  refine ⟨N, p, A, hN0, ?_, e.strictMono, ?_, ?_, hdensity⟩
  · intro i
    exact ⟨hpPrime i, by have := hpL i; omega⟩
  · intro i
    apply Arithmetic.cutoff_ten (hpPrime i).one_lt.le
    exact Arithmetic.cluster_cutoff_four hqbig (hpSquare i).le
  · intro i
    exact forbidden_card (p i)

/-- The fixed-(epsilon,eta) necessary consequence of the original proposed
    bound, written without real powers. Even this weaker bound is false. -/
def UniformTenthSieve : Prop :=
  ∃ k : ℕ, ∀ (N : ℕ) (p : Fin k → ℕ)
    (A : (i : Fin k) → Finset (ZMod (p i))),
    (∀ i, (p i).Prime) → StrictMono p →
    (∀ i, (p i) ^ 10 < N ^ 9) →
    (∀ i, (A i).card = (p i) / 2) →
    10 * (remaining N p A).card ≤ N

theorem not_uniform_tenth_sieve : ¬ UniformTenthSieve := by
  rintro ⟨k, hk⟩
  obtain ⟨N, p, A, _, hp, hm, he, hc, hd⟩ := counterexamples k 1
  exact (not_le_of_gt hd) (hk N p A (fun i => (hp i).1) hm he hc)

/-- Bridge from the exact integer exponent inequality to the conventional
    real-power notation N^(1 - epsilon), for epsilon = 1/10. -/
private lemma real_cutoff {p N : ℕ} (h : p ^ 10 < N ^ 9) :
    (p : ℝ) < (N : ℝ) ^ (1 - (1 / 10 : ℝ)) := by
  have hR : (p : ℝ) ^ 10 < (N : ℝ) ^ 9 := by exact_mod_cast h
  have hroot := Real.rpow_lt_rpow (by positivity : 0 ≤ (p : ℝ) ^ 10)
    hR (by norm_num : 0 < (1 / 10 : ℝ))
  have hleft : ((p : ℝ) ^ 10) ^ (1 / 10 : ℝ) = (p : ℝ) := by
    rw [← Real.rpow_natCast, ← Real.rpow_mul (by positivity : 0 ≤ (p : ℝ))]
    norm_num
  have hright : ((N : ℝ) ^ 9) ^ (1 / 10 : ℝ) =
      (N : ℝ) ^ (1 - (1 / 10 : ℝ)) := by
    rw [← Real.rpow_natCast, ← Real.rpow_mul (by positivity : 0 ≤ (N : ℝ))]
    norm_num
  simpa only [hleft, hright] using hroot

/-- The original uniform claim, using (p-1)/2 forbidden classes and
    independent exponent/density parameters. -/
def ErdosUniformSieve : Prop :=
  ∀ (epsilon eta : ℝ), 0 < epsilon → 0 < eta →
    ∃ k : ℕ, ∀ (N : ℕ) (p : Fin k → ℕ)
      (A : (i : Fin k) → Finset (ZMod (p i))),
      (∀ i, (p i).Prime) → StrictMono p →
      (∀ i, (p i : ℝ) < (N : ℝ) ^ (1 - epsilon)) →
      (∀ i, (A i).card = (p i - 1) / 2) →
      ((remaining N p A).card : ℝ) < eta * (N : ℝ)

/-- Negative answer to the uniform question. -/
theorem not_erdos_uniform_sieve : ¬ ErdosUniformSieve := by
  intro h
  obtain ⟨k, hk⟩ := h (1 / 10) (1 / 10) (by norm_num) (by norm_num)
  obtain ⟨N, p, A, _, hp, hm, he, hc, hd⟩ := counterexamples k 1
  have hc' : ∀ i, (A i).card = (p i - 1) / 2 := by
    intro i
    have hodd : p i % 2 = 1 :=
      (hp i).1.eq_two_or_odd.resolve_left (by have := (hp i).2; omega)
    have hh := hc i
    omega
  have hsmall := hk N p A (fun i => (hp i).1) hm
    (fun i => real_cutoff (he i)) hc'
  have hlarge : (N : ℝ) < 10 * ((remaining N p A).card : ℝ) := by
    exact_mod_cast hd
  nlinarith

/-- Even allowing a threshold N0 depending on epsilon, eta and k does not
    salvage the uniform proposed bound. -/
def ErdosEventualUniformSieve : Prop :=
  ∀ (epsilon eta : ℝ), 0 < epsilon → 0 < eta →
    ∃ k N0 : ℕ, ∀ (N : ℕ) (p : Fin k → ℕ)
      (A : (i : Fin k) → Finset (ZMod (p i))),
      N0 ≤ N →
      (∀ i, (p i).Prime) → StrictMono p →
      (∀ i, (p i : ℝ) < (N : ℝ) ^ (1 - epsilon)) →
      (∀ i, (A i).card = (p i - 1) / 2) →
      ((remaining N p A).card : ℝ) < eta * (N : ℝ)

theorem not_erdos_eventual_uniform_sieve : ¬ ErdosEventualUniformSieve := by
  intro h
  obtain ⟨k, N0, hk⟩ := h (1 / 10) (1 / 10) (by norm_num) (by norm_num)
  obtain ⟨N, p, A, hN0, hp, hm, he, hc, hd⟩ := counterexamples k N0
  have hc' : ∀ i, (A i).card = (p i - 1) / 2 := by
    intro i
    have hodd : p i % 2 = 1 :=
      (hp i).1.eq_two_or_odd.resolve_left (by have := (hp i).2; omega)
    have hh := hc i
    omega
  have hsmall := hk N p A hN0 (fun i => (hp i).1) hm
    (fun i => real_cutoff (he i)) hc'
  have hlarge : (N : ℝ) < 10 * ((remaining N p A).card : ℝ) := by
    exact_mod_cast hd
  nlinarith

/-- The fixed-1000-prime formulation follows from the all-k construction.
    This does not use Green44.green_44 or any declaration with an unfinished proof. -/
theorem fixed_1000_counterexample :
    ∃ (N : ℕ) (p : Fin 1000 → ℕ)
      (A : (i : Fin 1000) → Finset (ZMod (p i))),
      (∀ i, (p i).Prime) ∧ StrictMono p ∧
      (p 999) ^ 10 < N ^ 9 ∧
      (∀ i, (A i).card = (p i) / 2) ∧
      N < 10 * (remaining N p A).card := by
  obtain ⟨N, p, A, _, hp, hm, he, hc, hd⟩ := counterexamples 1000 1
  exact ⟨N, p, A, (fun i => (hp i).1), hm, he 999, hc, hd⟩

#print axioms JSP001007.counterexamples
#print axioms JSP001007.not_uniform_tenth_sieve
#print axioms JSP001007.not_erdos_uniform_sieve
#print axioms JSP001007.not_erdos_eventual_uniform_sieve
#print axioms JSP001007.fixed_1000_counterexample

end JSP001007

-- END EXACT MAIN BODY
