#!/usr/bin/env python3
"""Combine the three canonical modules without changing declaration bodies.

Generating this file is not compilation. The native gate independently
compiles both the module tree and this import-Mathlib-only file.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SOURCES = (
    ('JSP001007/Arithmetic.lean', 'import Lean\n', 'ARITHMETIC'),
    ('JSP001007/PrimeBlocks.lean', 'import Mathlib\n', 'PRIME BLOCKS'),
    ('JSP001007.lean',
     'import Mathlib\nimport JSP001007.Arithmetic\nimport JSP001007.PrimeBlocks\n', 'MAIN'),
)


def render(root: Path = ROOT) -> str:
    text = ('import Mathlib\n\n'
            '-- Generated by make_standalone.py; generation is not Lean verification.\n'
            '-- Declaration bodies below are copied exactly from the canonical modules.\n')
    for relative, header, label in SOURCES:
        source = (root / relative).read_text(encoding='utf-8')
        if not source.startswith(header):
            raise ValueError(f'Unexpected import header in {relative}')
        text += (f'\n-- BEGIN EXACT {label} BODY\n' + source[len(header):]
                 + f'\n-- END EXACT {label} BODY\n')
    return text


if __name__ == '__main__':
    (ROOT / 'JSP001007Standalone.lean').write_text(render(), encoding='utf-8')
