import JSP404

#print axioms JSP404.mem_angleValues
#print axioms JSP404.maxAngle_nonneg
#print axioms JSP404.angle_le_maxAngle
#print axioms JSP404.maxAngle_le
#print axioms JSP404.maxAngle_le_pi
#print axioms JSP404.hasLargeAngle_zero
#print axioms JSP404.hasLargeAngle_maxAngle
#print axioms JSP404.hasLargeAngle_iff_le_maxAngle
#print axioms JSP404.hasLargeAngle_mono
#print axioms JSP404.maxAngle_mono
#print axioms JSP404.guaranteed_zero
#print axioms JSP404.guaranteed_le_pi
#print axioms JSP404.guaranteed_bddAbove
#print axioms JSP404.alpha_nonneg
#print axioms JSP404.alpha_le_pi
#print axioms JSP404.le_alpha
#print axioms JSP404.alpha_le_of_configuration
#print axioms JSP404.alpha_le_maxAngle
#print axioms JSP404.guaranteed_mono
#print axioms JSP404.alpha_mono
#print axioms JSP404.guaranteed_alpha
#print axioms JSP404.guaranteed_iff_le_alpha
#print axioms JSP404.configurationMaxima_nonempty
#print axioms JSP404.configurationMaxima_bddBelow
#print axioms JSP404.alpha_eq_sInf
#print axioms JSP404.exists_configuration_maxAngle_lt
#print axioms JSP404.alpha_eq_of_bounds
#print axioms JSP404.hasLargeAngle_pi_div_three
#print axioms JSP404.guaranteed_pi_div_three
#print axioms JSP404.pi_div_three_le_alpha
#print axioms JSP404.realDigit_injective
#print axioms JSP404.realDigit_sub_ne_zero
#print axioms JSP404.realDigit_sub_eq_sign
#print axioms JSP404.realDigit_sub_same_base
#print axioms JSP404.exists_first_difference
#print axioms JSP404.binaryProjection_sub
#print axioms JSP404.binaryProjection_sub_factor
#print axioms JSP404.binaryResidual_zero
#print axioms JSP404.tendsto_binaryResidual
#print axioms JSP404.eventually_injective_binaryProjection
#print axioms JSP404.tendsto_binaryProjection_angle
#print axioms JSP404.alpha_two_pow_le_of_signed_directions
#print axioms JSP404.sum_free_binary_coordinates_le
#print axioms JSP404.card_le_two_pow_of_binary_separation
#print axioms JSP404.bipartite_cover_weighted_bound
#print axioms JSP404.card_le_two_pow_of_bipartite_cover
#print axioms JSP404.three_le_two_pow
#print axioms JSP404.szekeres_upper_bound
#print axioms JSP404.alpha_le_szekeres_upper
#print axioms JSP404.szekeres_lower_bound_alpha
#print axioms JSP404.classical_bounds_between_powers
#print axioms JSP404.alpha_le_self_index_upper
#print axioms JSP404.alpha_lt_pi
#print axioms JSP404.tendsto_binaryProjection_direction_angle
#print axioms JSP404.eventually_binaryProjection_angle_lt
#print axioms JSP404.eventually_injective_center_cluster
#print axioms JSP404.clusterWord_card
#print axioms JSP404.alpha_sum_two_pow_le_of_cluster_directions
#print axioms JSP404.angle_le_three_pi_div_four_of_inner
#print axioms JSP404.housePoint_injective
#print axioms JSP404.housePoint_angle_le
#print axioms JSP404.house_card
#print axioms JSP404.house_angle_le
#print axioms JSP404.three_pi_div_four_lt_four_pi_div_five
#print axioms JSP404.alpha_five_le_three_pi_div_four
#print axioms JSP404.alpha_five_lt_four_pi_div_five
#print axioms JSP404.alpha_five_ne_four_pi_div_five
#print axioms JSP404.not_guaranteed_five_four_pi_div_five
#print axioms JSP404.angle_lower_bound_of_two_cone_edges
#print axioms JSP404.not_two_cone_edges
#print axioms JSP404.coneGraph_colorable
#print axioms JSP404.card_le_two_pow_of_cone_cover
#print axioms JSP404.cone_cover_weighted_bound
#print axioms JSP404.finset_card_le_two_pow_of_direction_cover
#print axioms JSP404.hasLargeAngle_of_direction_cover
#print axioms JSP404.guaranteed_of_direction_cover
#print axioms JSP404.norm_circleDirection
#print axioms JSP404.angle_circleDirection
#print axioms JSP404.angle_circleDirection_le
#print axioms JSP404.circleDirection_pi
#print axioms JSP404.exists_polar_of_second_nonneg
#print axioms JSP404.exists_near_grid
#print axioms JSP404.equally_spaced_direction_cover
#print axioms JSP404.szekeres_lower_bound
#print axioms JSP404.angle_grid_directions
#print axioms JSP404.grid_direction_angle_bounds
#print axioms JSP404.signed_grid_direction_angle_le
#print axioms JSP404.signed_grid_direction_angle_le_real
#print axioms JSP404.five_in_lower_interval
#print axioms JSP404.transcribed_branch_at_three
#print axioms JSP404.source_branch_at_three
#print axioms JSP404.not_transcribed_lower_formula
#print axioms JSP404.source_branch_lt_transcribed
#print axioms JSP404.perturb_sub
#print axioms JSP404.perturb_sub_of_same_center
#print axioms JSP404.tendsto_perturb_sub
#print axioms JSP404.eventually_injective_perturb
#print axioms JSP404.perturb_angle_same_cluster
#print axioms JSP404.tendsto_angle_affine
#print axioms JSP404.tendsto_perturb_angle
#print axioms JSP404.exists_configuration_of_cluster_angles
#print axioms JSP404.alpha_le_of_cluster_angles
#print axioms JSP404.mul_le_sub_one_of_normalized_cap
#print axioms JSP404.floor_pair_exponent_bound
#print axioms JSP404.centerExponent_bound
#print axioms JSP404.three_powers_le_two_pow_of_at_most_one_high
#print axioms JSP404.three_powers_le_five_of_not_all_high
#print axioms JSP404.three_centers_not_two_high
#print axioms JSP404.three_centers_not_all_high
#print axioms JSP404.three_center_bound_small_delta
#print axioms JSP404.three_center_bound
