import PerfectDifference

#print axioms PerfectDifference.missing_pair
#print axioms PerfectDifference.avoid_one
#print axioms PerfectDifference.avoid_two
#print axioms PerfectDifference.avoid_shift
#print axioms PerfectDifference.sidon_insert_pair
#print axioms PerfectDifference.bad_card
#print axioms PerfectDifference.missing_small
#print axioms PerfectDifference.firstMissing_spec
#print axioms PerfectDifference.firstMissing_le
#print axioms PerfectDifference.firstMissing_bound
#print axioms PerfectDifference.nextDiff_bound
#print axioms PerfectDifference.nextBase_fresh
#print axioms PerfectDifference.extend_card
#print axioms PerfectDifference.subset_extend
#print axioms PerfectDifference.extend_sidon
#print axioms PerfectDifference.new_endpoint_bound
#print axioms PerfectDifference.stage_monotone
#print axioms PerfectDifference.stage_card
#print axioms PerfectDifference.stage_sidon
#print axioms PerfectDifference.stage_positive
#print axioms PerfectDifference.differences_mono
#print axioms PerfectDifference.nextDiff_represented
#print axioms PerfectDifference.stage_covers
#print axioms PerfectDifference.bound_monotone
#print axioms PerfectDifference.stage_bound
#print axioms PerfectDifference.seed_subset_completion
#print axioms PerfectDifference.completion_positive
#print axioms PerfectDifference.completion_sidon
#print axioms PerfectDifference.completion_representation
#print axioms PerfectDifference.completion_perfect
#print axioms PerfectDifference.completion_endpoint_bound
#print axioms PerfectDifference.completion_count_witness
#print axioms PerfectDifference.completion_unbounded
#print axioms PerfectDifference.exists_perfect_cubic
#print axioms PerfectDifference.completion_infinite
#print axioms PerfectDifference.finite_seed_completion
