name = "jsp669"
version = "0.1.0"
defaultTargets = ["Proof"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "1fe0a51a5ecdee23c424b6e29ecb1d40eb35316d"

[[lean_lib]]
name = "Proof"
