import MagicWeights

#print axioms MagicWeights.pair_pencil
#print axioms MagicWeights.incidence_sum
#print axioms MagicWeights.weight_equation
#print axioms MagicWeights.degree_sub_pos
#print axioms MagicWeights.reciprocalSum_nonneg
#print axioms MagicWeights.total_weight
#print axioms MagicWeights.weight_eq_formula
#print axioms MagicWeights.weakMagic_unique
#print axioms MagicWeights.magic_iff_formula
#print axioms MagicWeights.weightFormula_alternative
#print axioms MagicWeights.formula_pos_iff
#print axioms MagicWeights.formula_line_iff
#print axioms MagicWeights.magic_iff_degreeCertificate
#print axioms MagicWeights.degree_gt_one
#print axioms MagicWeights.full_line_unique
#print axioms MagicWeights.lines_empty_of_small
#print axioms MagicWeights.magic_of_full_line
#print axioms MagicWeights.magic_iff_all_cases
#print axioms MagicWeights.mem_lineBlock
#print axioms MagicWeights.mem_determinedLines
#print axioms MagicWeights.determinedLines_linearSpace
#print axioms MagicWeights.geometric_magic_iff
#print axioms MagicWeights.weightFormula_cast
#print axioms MagicWeights.magic_cast
#print axioms MagicWeights.real_magic_iff_rational
#print axioms MagicWeights.accepts_iff
#print axioms MagicWeights.rejects_iff
#print axioms MagicWeights.planar_accepts_iff
#print axioms MagicWeights.magic_determinedLines_iff
#print axioms MagicWeights.geometric_accepts_iff_common_sum
#print axioms MagicWeights.fivePoint_linearSpace
#print axioms MagicWeights.fivePoint_rejected
#print axioms MagicWeights.fivePoint_no_magic
#print axioms MagicWeights.failedFano_linearSpace
#print axioms MagicWeights.failedFano_accepted
#print axioms MagicWeights.failedFano_magic
