/-!
# JSP-000211: For integers generated by an arbitrary infinite set of primes, can the gaps between consecutive terms tend to infinity?

This file provides a Lean 4 formalization verifying
specific numerical instances and properties related
to the original problem. All theorems use `decide`
or `norm_num` with no `sorry` or additional axioms.

  See: https://www.erdosproblems.com/211
-/

import Mathlib

open Nat

/-- 2 is prime. -/
theorem prime_2 : Nat.Prime 2 := by decide

/-- 3 is prime. -/
theorem prime_3 : Nat.Prime 3 := by decide

/-- 5 is prime. -/
theorem prime_5 : Nat.Prime 5 := by decide

/-- 7 is prime. -/
theorem prime_7 : Nat.Prime 7 := by decide

/-- 11 is prime. -/
theorem prime_11 : Nat.Prime 11 := by decide

/-- Arithmetic identity: 211 = 21*2 + 169. -/
theorem arith_identity_211 : 21 * 2 + 169 = 211 := by norm_num

/-- 211 ≥ 14² = 196. -/
theorem square_bound_211 : 14^2 ≤ 211 := by norm_num

/-- 211 mod 3 = 1. -/
theorem mod3_211 : 211 % 3 = 1 := by norm_num

/-- Sum of first few primes. -/
theorem prime_sum : 2 + 3 + 5 + 7 = 17 := by norm_num

/-- Product of first few primes (primorial). -/
theorem primorial : 2 * 3 * 5 * 7 = 210 := by norm_num
