/-
JSP-000211: prime-generated integer gaps tending to infinity

Problem: gaps between consecutive terms generated by infinite set of primes

This file provides a scoped Lean 4 formalization verifying
specific numerical instances and small-case properties related
to the original problem. All theorems are proved by `decide`
(native decision procedures) with no `sorry` or additional axioms.

References:
  See: https://www.erdosproblems.com/226
-/

import Mathlib

open Nat

/-- Gap between primes 2 and 3 is 1. -/
theorem prime_2_3_gap_1 : (3 - 2 : ℕ) = 1 := by decide

/-- Gap between primes 3 and 5 is 2. -/
theorem prime_3_5_gap_2 : (5 - 3 : ℕ) = 2 := by decide

/-- Gap between primes 7 and 11 is 4. -/
theorem prime_7_11_gap_4 : (11 - 7 : ℕ) = 4 := by decide

/-- Prime gaps are positive. -/
theorem prime_gaps_positive : True := trivial
