name = "jsp000554"
version = "0.1.0"
defaultTargets = ["Jsp000554"]

[[lean_lib]]
name = "Jsp000554"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.34.0"
