name = "erdos866"
version = "0.1.0"
defaultTargets = ["Erdos866"]

[[lean_lib]]
name = "Erdos866"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.34.0"
